### ISSUE TITLE
Problem saving the generated pdf

### ISSUE THREAD

**Issue by ygoltrant** [allefeld/atom-pandoc-pdf#3]
Hi !
I'm having issues saving the generated pdf. When I click on "Save generated pdf" it opens my file manager, enabling me to save it, but it does not save it (I cannot find it where I wanted it to be saved).
Let me know if I can bring you further informations.

By the way, it would be nice if we could choose to automatically have the generated pdf saved in our directory.

**Comment by allefeld** [comment]
I've run into that problem myself, it seems to be related to an API change in Electron.

I've just published a new version 0.1.2, please update and let me know whether that fixes the problem.

**Comment by ygoltrant** [comment]
Great ! Thanks for the update. Problem solved !

**Comment by allefeld** [comment]
fixed by 44e57228b39ac412b266968c2b2d971d0d785119
